<a href="https://colab.research.google.com/github/Payal930-ui/Customer-Behaviour-Analysis/blob/main/customer_behaviour.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/customer_shopping_behavior.csv')

In [ ]:
df=pd.read_csv('/content/customer_shopping_behavior.csv')

In [ ]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [ ]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [ ]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [ ]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [ ]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [ ]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [ ]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [ ]:
#Create a column age group
labels=['young Adult','Adult','Middle-aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  young Adult
2   50  Middle-aged
3   21  young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  young Adult
8   26  young Adult
9   57  Middle-aged

In [ ]:
#purchase  frequency days
frequency_mapping={
    'Fortnightly':14,
    'Monthly':30,
    'Quarterly':90,
    'Weekly':7,
    'Annually':365,
    'Bi-Weekly':14,
    'Every  3 Months':90
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [ ]:
df[['discount_applied','promo_code_used']].head()

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes

In [ ]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [ ]:
df=df.drop('promo_code_used',axis=1)

In [ ]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

### Save DataFrame to SQLite Database

To save the `df` DataFrame to a SQLite database, we'll use Python's built-in `sqlite3` module to create a database connection and the pandas `to_sql()` method to write the DataFrame to a table within that database.

In [ ]:
import sqlite3

# Define the SQLite database file name
sqlite_db_name = 'customer_behavior.db'

# Create a connection to the SQLite database
# If the database file doesn't exist, it will be created.
conn = sqlite3.connect(sqlite_db_name)

# Save the DataFrame to a table named 'customer_data' in the SQLite database
# if_exists='replace' will overwrite the table if it already exists
# index=False prevents pandas from writing the DataFrame index as a column in the SQL table
df.to_sql('customer', conn, if_exists='replace', index=False)

# Close the connection
conn.close()

print(f"DataFrame successfully saved to SQLite database '{sqlite_db_name}' in table 'customer'.")

DataFrame successfully saved to SQLite database 'customer_behavior.db' in table 'customer'.

You can verify the data has been written by reading it back into a new DataFrame:

In [ ]:
# Verify by reading the data back from SQLite
conn = sqlite3.connect(sqlite_db_name)
df_from_sqlite = pd.read_sql_query("SELECT * FROM customer ", conn)


display(df_from_sqlite.head(20))

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,young Adult,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,young Adult,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365.0
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,14,Venmo,Weekly,Middle-aged,7.0
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,49,Cash,Quarterly,Senior,90.0
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,19,Credit Card,Weekly,young Adult,7.0
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8,Venmo,Annually,young Adult,365.0
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,4,Cash,Quarterly,Middle-aged,90.0
10,11,53,Male,Shoes,Footwear,34,Arkansas,L,Purple,Fall,4.1,Yes,Store Pickup,Yes,26,Bank Transfer,Bi-Weekly,Middle-aged,14.0
11,12,30,Male,Shorts,Clothing,68,Hawaii,S,Olive,Winter,4.9,Yes,Store Pickup,Yes,10,Bank Transfer,Fortnightly,young Adult,14.0
12,13,61,Male,Coat,Outerwear,72,Delaware,M,Gold,Winter,4.5,Yes,Express,Yes,37,Venmo,Fortnightly,Senior,14.0
13,14,65,Male,Dress,Clothing,51,New Hampshire,M,Violet,Spring,4.7,Yes,Express,Yes,31,PayPal,Weekly,Senior,7.0
14,15,64,Male,Coat,Outerwear,53,New York,L,Teal,Winter,4.7,Yes,Free Shipping,Yes,34,Debit Card,Weekly,Senior,7.0
15,16,64,Male,Skirt,Clothing,81,Rhode Island,M,Teal,Winter,2.8,Yes,Store Pickup,Yes,8,PayPal,Monthly,Senior,30.0
16,17,25,Male,Sunglasses,Accessories,36,Alabama,S,Gray,Spring,4.1,Yes,Next Day Air,Yes,44,Debit Card,Bi-Weekly,young Adult,14.0
17,18,53,Male,Dress,Clothing,38,Mississippi,XL,Lavender,Winter,4.7,Yes,2-Day Shipping,Yes,36,Venmo,Quarterly,Middle-aged,90.0
18,19,52,Male,Sweater,Clothing,48,Montana,S,Black,Summer,4.6,Yes,Free Shipping,Yes,17,Cash,Weekly,Middle-aged,7.0
19,20,66,Male,Pants,Clothing,90,Rhode Island,M,Green,Summer,3.3,Yes,Standard,Yes,46,Debit Card,Bi-Weekly,Senior,14.0

# **Q1. What is the total revenue generated by the male vs  the female customers?**

In [ ]:
df_from_sqlite=pd.read_sql_query("SELECT gender,SUM(purchase_amount) AS revenue  FROM customer GROUP BY gender",conn)
display(df_from_sqlite.head())

   gender  revenue
0  Female    75191
1    Male   157890

# **Q2. Which customer used a discount but still spent more than the averagge purchase amount?**

In [ ]:
df_from_sqlite=pd.read_sql_query("SELECT customer_id,purchase_amount from customer where discount_applied='Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer)",conn)
display(df_from_sqlite.head())

   customer_id  purchase_amount
0            2               64
1            3               73
2            4               90
3            7               85
4            9               97

# **Which are the top 5 products with the highest average review rating ?**

In [ ]:
df_from_sqlite=pd.read_sql_query("SELECT item_purchased,ROUND(AVG(review_rating),2) AS avg_rating FROM customer GROUP BY item_purchased ORDER BY avg_rating DESC LIMIT 5",conn)
display(df_from_sqlite.head())

  item_purchased  avg_rating
0         Gloves        3.86
1        Sandals        3.84
2          Boots        3.82
3            Hat        3.80
4        T-shirt        3.78

# **Q3. Compare the average purchase  ammount between standard and express shipping.**

In [ ]:
df_from_sqlite=pd.read_sql_query("SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS average_purchase_amt FROM customer WHERE shipping_type IN ('Standard','Express') GROUP BY shipping_type",conn)
display(df_from_sqlite.head())

  shipping_type  average_purchase_amt
0       Express                 60.48
1      Standard                 58.46

# **Q5. Do subscribed customers spend more? Compare average and total revenue of subscriber and non subscribers.**

In [ ]:
df_from_sqlite=pd.read_sql_query("SELECT subscription_status,COUNT(customer_id)AS total_customers, ROUND(AVG(purchase_amount),2) AS avg_spend,ROUND(SUM(purchase_amount),2)AS total_revenue FROM customer GROUP BY subscription_status ORDER BY total_revenue,avg_spend DESC",conn)
display(df_from_sqlite.head())

  subscription_status  total_customers  avg_spend  total_revenue
0                 Yes             1053      59.49        62645.0
1                  No             2847      59.87       170436.0

# **Q6. WHICH 5 products have the highest percentage of purchases with discounts applied?**

In [ ]:
df_from_sqlite=pd.read_sql_query("SELECT item_purchased, 100 * SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*) AS discount_rate FROM customer GROUP BY item_purchased ORDER BY discount_rate DESC LIMIT 5 ",conn)
display(df_from_sqlite.head())

  item_purchased  discount_rate
0            Hat             50
1       Sneakers             49
2           Coat             49
3        Sweater             48
4          Pants             47

# **Q7. Segment customers into new, returning and loyal based on their total no. of previous purchase,and show the count oof each segment.**

In [ ]:
df_from_sqlite=pd.read_sql_query("""WITH customer_type AS(SELECT customer_id,previous_purchases,CASE
WHEN previous_purchases=1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment FROM customer )
SELECT customer_segment,COUNT(*) AS "No. of customers" FROM customer_type GROUP BY customer_segment""",conn)
display(df_from_sqlite.head())

  customer_segment  No. of customers
0            Loyal              3116
1              New                83
2        Returning               701

# **Q8. What are the top 3 most purchased products with each category?**

In [ ]:
df_from_sqlite=pd.read_sql_query("""WITH item_counts AS (SELECT category,item_purchased,COUNT(customer_id) AS total_orders,
ROW_NUMBER()OVER(partition by category ORDER  BY COUNT(customer_id)DESC)  AS item_rank FROM customer GROUP BY category,item_purchased)
 SELECT item_rank,category,item_purchased,total_orders FROM item_counts WHERE item_rank<=3""",conn)
display(df_from_sqlite.head())

   item_rank     category item_purchased  total_orders
0          1  Accessories        Jewelry           171
1          2  Accessories     Sunglasses           161
2          3  Accessories           Belt           161
3          1     Clothing          Pants           171
4          2     Clothing         Blouse           171

# **Q9. Are customers who are repeat buyers (more than 5 previous purchases)also likely to subscribe?**

In [ ]:
df_from_sqlite=pd.read_sql_query("""SELECT subscription_status,COUNT(customer_id) AS repeat_buyers FROM customer where previous_purchases >5 GROUP BY subscription_status""",conn)
display(df_from_sqlite.head())

  subscription_status  repeat_buyers
0                  No           2518
1                 Yes            958

# **Q10. What is the revenue contribution of each group?**

In [ ]:
df_from_sqlite=pd.read_sql_query("SELECT age_group,SUM(purchase_amount) AS total_revenue FROM customer GROUP BY age_group ORDER BY total_revenue DESC",conn)
display(df_from_sqlite.head())

     age_group  total_revenue
0  young Adult          62143
1  Middle-aged          59197
2        Adult          55978
3       Senior          55763

In [ ]:
df = pd.read_sql_query("""
SELECT *
FROM customer
""", conn)

df.to_csv("customer_behavior_powerbi.csv", index=False)

In [ ]:
from google.colab import files

files.download("customer_behavior_powerbi.csv")